# 导航菜单配置
[[main]]
name = 'Home'
pageRef = '/'
weight = 10

[[main]]
name = "About"
pageRef = "/about/"
weight = 20

[[main]]
name = "Contact"
pageRef = "/contact/"
weight = 30

[[main]]
name = "Guestbook"
pageRef = "/guestbook/"
weight = 40

[[main]]
name = "Search"
pageRef = "/search/"
weight = 50
